[build]
watchPatterns = ["backend/apps/main/**", "backend/packages/**", "packages/**"]
builder = "DOCKERFILE"
dockerfilePath = "backend/apps/main/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
