[build]
watchPatterns = ["backend/apps/**", "backend/packages/**", "packages/**"]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
