[build]
watchPatterns = ["backend/apps/auth/**", "backend/packages/**", "packages/**"]
builder = "DOCKERFILE"
dockerfilePath = "backend/apps/auth/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
