[build]
watchPatterns = ["backend/apps/api-gateway/**", "backend/packages/**", "packages/**"]
builder = "DOCKERFILE"
dockerfilePath = "backend/apps/api-gateway/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
