[build]
watchPatterns = ["admin/apps/main/**", "admin/packages/**", "packages/**"]
builder = "DOCKERFILE"
dockerfilePath = "admin/apps/main/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
