[build]
watchPatterns = ["admin/apps/**", "admin/packages/**", "packages/**"]
builder = "DOCKERFILE"
dockerfilePath = "admin/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
